name: Java Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
  
    # Step 5: Run Selenium tests
    - name: Run Selenium Tests
      run: mvn clean test

   # Step 6: TestNg Report
    - name: Upload TestNG report artifact
      uses: actions/upload-artifact@v3
      with:
          name: testng-report
          path: target/surefire-reports

  # Step 7: TestNg Report on github
    - name: Display TestNG Summary in Job Summary
      run: |
          echo "## TestNG Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Total Tests: $(grep -o '<test-method status="PASS"' target/surefire-reports/testng-results.xml | wc -l)" >> $GITHUB_STEP_SUMMARY
          echo "- Failed Tests: $(grep -o '<test-method status="FAIL"' target/surefire-reports/testng-results.xml | wc -l)" >> $GITHUB_STEP_SUMMARY
          echo "- Skipped Tests: $(grep -o '<test-method status="SKIP"' target/surefire-reports/testng-results.xml | wc -l)" >> $GITHUB_STEP_SUMMARY

