# .github/workflows/ci.yml
name: Build Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Archive Code
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Clean using Maven (optional)
        run: mvn clean

      - name: Create ZIP package
        run: |
          mkdir output
          powershell Compress-Archive -Path * -DestinationPath output/selenium-code.zip

      - name: Upload ZIP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: selenium-code-zip
          path: output/selenium-code.zip
