# .github/workflows/cd.yml
name: Deployment Pipeline (Manual Trigger)

on:
  workflow_dispatch:

jobs:
  deploy-and-run-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout ci-artifacts branch
        uses: actions/checkout@v4
        with:
          ref: ci-artifacts

      - name: Extract selenium-code.zip
        run: Expand-Archive -Path selenium-code.zip -DestinationPath extracted

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run TestNG Tests
        working-directory: extracted
        run: mvn test -DsuiteXmlFile=testng.xml

      - name: Upload Test Reports
        if: always()  # ensures it runs even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: testng-reports
          path: extracted/reports
