# .github/workflows/cd.yml
name: Deployment Pipeline (Manual Trigger)

on:
  workflow_dispatch:

jobs:
  deploy-and-run-tests:
    name: Run TestNG Tests
    runs-on: windows-latest

    steps:
      - name: Download Artifact to folder
        uses: actions/download-artifact@v4
        with:
          name: selenium-code-zip
          path: artifact

      - name: List files (debug)
        run: dir artifact

      - name: Extract ZIP to extracted/
        run: Expand-Archive -Path artifact/selenium-code.zip -DestinationPath extracted

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run TestNG Suite from extracted
        working-directory: extracted
        run: mvn test -DsuiteXmlFile=testng.xml
